CREATE TABLE teams
	( id    SERIAL PRIMARY KEY
	, name  VARCHAR(64) NOT NULL UNIQUE
	);

CREATE TABLE users
	( id     SERIAL PRIMARY KEY
	, name   VARCHAR(64) NOT NULL UNIQUE
	, email  VARCHAR(128) NOT NULL UNIQUE
	, teamId INTEGER REFERENCES teams(id)
	);

CREATE TABLE auths
	( id      UUID PRIMARY KEY
	, userId  INTEGER NOT NULL REFERENCES users(id)
	, expires TIMESTAMP WITH TIME ZONE
	);
